stages:
- test
- deploy

sast:
  stage: test

cdk-deploy:
  # Use Node 16 on Alpine
  image: node:16-alpine
  stage: deploy
  script:
    - apk --no-cache add curl zip
    - 'curl --location --output frontend.zip "$ARTIFACT_DOWNLOAD_URL"'
    - unzip frontend.zip
    - mv dist/ frontend
    - npm install --progress=false
    - npm run build
    - npm run cdk bootstrap
    - npm run cdk deploy

include:
- template: Security/SAST.gitlab-ci.yml
